### ISSUE TITLE
break with vue-cli beta 10

### ISSUE THREAD

**Issue by ellis2323** [davidwallacejackson/vue-cli-plugin-unit-karma#2]
https://github.com/vuejs/vue-cli/issues/1205
PluginAPI.setMode() has been removed. Instead, for a plugin to sepcify the default mode for a registered command, the plugins should expose module.exports.defaultModes in the form of { [commandName]: mode }.

**Comment by davidwallacejackson** [comment]
I think this is fixed as of the most recent release -- please let me know if you're still seeing it!
